spring.application.name=gateway-service
server.port=8080

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Allow the Gateway to route to its own internal controllers for fallbacks
spring.cloud.gateway.forwarded.enabled=true